
services:
  # 1. O container do Ollama (Gerenciador local do LLM)
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - gamedar-network

  # 2. O Servidor MCP
  mcp-gateway:
    build: ./mcp_server
    container_name: mcp-gateway
    ports:
      - "8000:8000"
    networks:
      - gamedar-network

  # 3. Microsserviço de IA (LangChain + FastAPI) ATUALIZADO COM RAG
  ia-service:
    build:
      context: ./modulo-ia
      dockerfile: Dockerfile
    container_name: ia-service
    ports:
      - "8002:8002"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
    depends_on:
      chromadb:
        condition: service_healthy
      ollama:
        condition: service_started
      mcp-gateway:
        condition: service_started
    networks:
      - gamedar-network
    volumes:
      - ./ia:/app # Hot-reload durante desenvolvimento

  # 4. API Gateway (Ponte com o Frontend)
  api-gateway:
    build: ./gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - IA_SERVICE_URL=http://ia-service:8002
    depends_on:
      - ia-service
    networks:
      - gamedar-network

  # 5. BANCO VETORIAL (ChromaDB)
  chromadb:
    image: chromadb/chroma:0.5.3
    container_name: chromadb
    ports:
      - "8005:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
    networks:
      - gamedar-network
    #healthcheck:
      #test: ["CMD-SHELL", "wget -qO- http://localhost:8000/api/v1/heartbeat || exit 1"]
      #interval: 10s
      #timeout: 5s
      #retries: 10
      #start_period: 20s

  # 6. INGESTÃO RAG (job único)
  rag-ingest:
    build:
      context: ./modulo-ia
      dockerfile: Dockerfile
    container_name: rag-ingest
    command: python ingest.py
    environment:
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_CLIENT_SECRET=${TWITCH_CLIENT_SECRET}
      - OLLAMA_BASE_URL=http://ollama:11434
      - CHROMA_HOST=chromadb
      - CHROMA_PORT=8000
    depends_on:
      chromadb:
        condition: service_started
      ollama:
        condition: service_started
    networks:
      - gamedar-network
    profiles:
      - ingest

networks:
  gamedar-network:
    driver: bridge

volumes:
  ollama_data:
  chroma_data: